### ISSUE TITLE
Links don't work after exporting PDF

### ISSUE THREAD

**Issue by sunkoto** [adrian-fuertes/typora-notion-theme#19]
Hi , I love this theme very much. Thank you so much for making this theme. 
Everything works perfectly except when I want to go to the PDF file, the link doesn't work fine.

Examples are as follows. This works fine:
`https://www.google.com`

But this will not work properly:
`[Google](https://www.google.com)`

When I hit this “Google” in the PDF file, nothing happens. It should open a corresponding webpage when i click on “Google”.

Many thanks and looking forward to a fix for this issue.

My software operating environment:
Macos 13.1;
Typora 1.5.5 (6702)

**Comment by adrian-fuertes** [comment]
Hey @sunkoto! Thank you so much for creating this issue. I have encountered this problem before but it did not occur to me that it might be related the theme itself. After trying a few things, it turns out that accessing the `opacity` property of `.md-def-url` was making links unclickable after export (I have not figured out why yet). 

The issue has been addressed and incorporated into the [latest release](https://github.com/adrian-fuertes/typora-notion-theme/releases/tag/v1.2.1)!
