### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by enricodarodda** [adrian-fuertes/typora-notion-theme#6]
Hi,
i wanted to point out that w.r.t. the default "Github" theme, the size of the font is smaller; would it be possible to increase it as the one of github? Yes, your answer would be to set a different font size within the settings, and that would be perfectly fine if not for the fact that it increases the size of all the characters, and i believe that in this theme the dimension of code chunks' is perfect, and unfortunately it will be altered.
So, my question is, would it be possible to increase just the size of the plain text?

**Comment by adrian-fuertes** [comment]
Hey! The default font is set to **14px**, since I always use a custom font size I didn't realize that other themes used a large default. The Github theme uses **16px**, so I will set the default font to 16px to match that. I'll add some more fixes and make a new release. 

Thank you for your comment and hope that helps!
