### ISSUE TITLE
Checkbox and top bar misaligned under unimode in windows 10

### ISSUE THREAD

**Issue by Maizehsu** [adrian-fuertes/typora-notion-theme#8]
#### Basic info:
System: Windows 10
Typora Version: 1.2.0
Theme: Notion Light/Dark/Darker Enhanced/Not

#### Problem 1.
![image](https://user-images.githubusercontent.com/71319123/160329335-4233d9db-76cd-43c1-a348-b8caf6034ef3.png)
It seems that the ✔ in the checkbox is alligned a bit below the central line.

#### Problem 2.
![e646ea94d3fec7435a1db06ff47ce0e](https://user-images.githubusercontent.com/71319123/160329727-56449d04-7716-4cba-853e-939f5824fb51.png)
The three buttons responsible for maximizing, minimizing and closing the windows are alligned a bit below the top line, creating a height difference with the top line in the left
![9f0d6706cdf32a3a68cb5c56cdbb4a2](https://user-images.githubusercontent.com/71319123/160330301-5e251b4b-087a-43e1-b524-8d742e718203.png)
This picture showing the red close button would display the height difference clearer.

#### Observation:
The diviation from the central line in both problems looks the same, so I assume that they are caused by the same problem. I tried a few more themes, the misalignment in problem 2 are observed in theme "Newsprint", but others like "Gitbook" and "Github" performs well. I guess it's due to some compatability issue between macOS and windows in css, please check it out.

**Comment by Neptunian-shushu** [comment]
Yes, I agree.

**Comment by adrian-fuertes** [comment]
Hey @Maizehsu and @Neptunian-shushu! Thank you for bringing theses issues up. Both problems have been addressed in the [latest release](https://github.com/adrian-fuertes/typora-notion-theme/releases/tag/v1.1.2).

Regarding the **first problem**, it is not completely possible to fix the to-do list alignment. It will always clip at smaller text sizes, making it seem it is not aligned. The tick mark size is now relative to the text size, so it should mostly fix this problem.

The **second problem** has been fixed by changing the menu bar color. For some reason the top-bar size in Windows is smaller than the window management UI. I really wish it wasn't, since having a differently colored top bar looks quite nice... but there's nothing I can do about that.

Thanks again! Let me know if you have any other issues.
